const otherSmallZonePointJson  = {
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "Name":"植松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.710343,
               137.757704
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"将監町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.7150174,
               137.7546787
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"神立町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.717714,
               137.753659
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西塚町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.719206,
               137.757240
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上西町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.723540,
               137.761133
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"丸塚町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.728082,
               137.758968
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上新屋町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.731456,
               137.757232
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"宮竹町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.719800,
               137.763047
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大蒲町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.714502,
               137.767119
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"子安町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.712039,
               137.762584
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"和田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.719971,
               137.771202
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"天龍川町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.719167,
               137.779062
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"篠ケ瀬町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.728938,
               137.775282
            ]
         }
      },
      {
         "type":"Feature",
         "properties": {
            "Name":"北島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.730604,
               137.782156
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"薬師町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.724517,
               137.782156
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"薬新町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.724579,
               137.787127
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"安新町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.730562,
               137.787671
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"安間町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.722932,
               137.791367
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"材木町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.716580,
               137.791538
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"龍光町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.717331,
               137.785356
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"長鶴町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.7135646,
               137.7777754
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"白鳥町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.744073,
               137.799313
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"松小池町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.736194,
               137.791848
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中里町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.737403,
               137.798189
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.730438,
               137.798933
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"国吉町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.722763,
               137.797225
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上石田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.753117,
               137.787048
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"市野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.747750,
               137.772431
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"小池町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.747843,
               137.758039
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.736378,
               137.758351
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"原島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.730032,
               137.768986
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"天王町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.737997,
               137.772284
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"下石田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.740074,
               137.784553
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"笠井町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.768999,
               137.795374
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"笠井上町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.777249,
               137.799940
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"笠井新田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.764501,
               137.787791
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"豊町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.773469,
               137.808701
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"豊西町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.761149,
               137.809312
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"恒武町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.763214,
               137.798798
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"貴平町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.754750,
               137.795139
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"常光町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.752301,
               137.805189
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"流通元町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.744131,
               137.789723
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中郡町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.773402,
               137.779338
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西ケ崎町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.776474,
               137.767929
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.764753,
               137.780364
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大瀬町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.759443,
               137.768151
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"積志町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.768434,
               137.765770
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"有玉北町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.767604,
               137.754443
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"有玉南町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.754457,
               137.748963
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"有玉西町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.757333,
               137.740043
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"半田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.771834,
               137.751132
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"有玉台"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.762829,
               137.739943
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"半田山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.773270,
               137.741307
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西山町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.742561,
               137.690134
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"神ケ谷町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.722808,
               137.675060
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大久保町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.718884,
               137.655473
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"神原町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.734182,
               137.672552
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"入野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.699205,
               137.681504
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西鴨江町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.706412,
               137.662921
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"志都呂町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.703241,
               137.653441
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"伊左地町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.748212,
               137.669532
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐浜町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.747867,
               137.646712
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大人見町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.735388,
               137.653297
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"古人見町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.727153,
               137.633545
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"和地町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.764774,
               137.654828
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"湖東町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.762950,
               137.676132
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大山町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.780344,
               137.682440
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"和光町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.783477,
               137.675263
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"深萩町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.775225,
               137.655244
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"平松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.757714,
               137.634927
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"呉松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.772182,
               137.633971
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"白洲町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.747552,
               137.623817
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"舘山寺町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.760702,
               137.617506
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"庄内町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.751702,
               137.604806
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"協和町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.746461,
               137.614126
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"庄和町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.740918,
               137.601481
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"村櫛町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.728295,
               137.594843
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"篠原町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.684823,
               137.663456
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"坪井町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.683836,
               137.646275
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"馬郡町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.683976,
               137.634492
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大平台"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.714401,
               137.682930
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西都台町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.702788,
               137.661198
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"志都呂"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.703030,
               137.653226
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"舞阪町舞阪"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.685136,
               137.613700
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"舞阪町長十新田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.680093,
               137.627480
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"舞阪町浜田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.682458,
               137.622344
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"舞阪町弁天島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.694029,
               137.602252
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"雄踏町宇布見"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.702650,
               137.632769
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"雄踏町山崎"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.720590,
               137.635237
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"雄踏 "
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.694617,
               137.643593
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"渡瀬町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.706464,
               137.761347
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三和町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.705048,
               137.767421
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"飯田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.707540,
               137.776764
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"青屋町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.715335,
               137.777444
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"鶴見町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.709883,
               137.791545
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"新貝町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.703127,
               137.789497
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大塚町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.697537,
               137.788740
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"下飯田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.699390,
               137.778658
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"頭陀寺町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.698956,
               137.757794
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"本郷町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.697307,
               137.763713
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西伝寺町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.702343,
               137.763849
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"安松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.695978,
               137.769034
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"石原町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.692013,
               137.773666
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"金折町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.692922,
               137.782048
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"老間町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.690625,
               137.789748
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"古川町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.689498,
               137.776370
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"立野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.685852,
               137.773553
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"四本松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.684294,
               137.767223
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"芳川町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.690842,
               137.765588
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"恩地町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.687213,
               137.760799
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"参野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.692778,
               137.757728
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"都盛町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.686047,
               137.755941
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大柳町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.678252,
               137.757702
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"鼡野町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.676396,
               137.763642
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"御給町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.675493,
               137.769007
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"下江町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.680633,
               137.770158
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"富屋町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.679265,
               137.775283
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.683998,
               137.779872
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.681217,
               137.785601
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"長田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.670469,
               137.777465
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"河輪町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.674294,
               137.784584
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三新町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.663617,
               137.784914
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"江之島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.664082,
               137.755487
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.661114,
               137.767365
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"福島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.663493,
               137.761650
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"松島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.660681,
               137.778558
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"遠州浜"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.656510,
               137.767763
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"楊子町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.693360,
               137.746171
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.688791,
               137.745986
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"瓜内町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.687554,
               137.734847
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"白羽町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.674170,
               137.734630
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中田島町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.669684,
               137.742392
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"寺脇町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.680244,
               137.748564
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"福塚町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.674347,
               137.752980
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"法枝町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.675458,
               137.720623
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"田尻町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.675942,
               137.723331
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"新橋町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.683049,
               137.706403
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"堤町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.677452,
               137.704362
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"米津町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.674143,
               137.713664
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"小沢渡町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.680698,
               137.682382
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"倉松町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.673904,
               137.692542
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"卸本町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.672470,
               137.725213
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"高塚町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.690290,
               137.680016
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"増楽町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.691068,
               137.692085
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"若林町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.691819,
               137.702818
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東若林町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.691016,
               137.712348
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"初生町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.766981,
               137.726463
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三方原町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.783202,
               137.710559
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東三方町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.780398,
               137.730980
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"豊岡町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.789675,
               137.726978
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三幸町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.800848,
               137.722209
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大原町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.799806,
               137.737699
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"都田町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.826114,
               137.727142
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"滝沢町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.861896,
               137.726934
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"鷲沢町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.846116,
               137.710797
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"根洗町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.796631,
               137.704164
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"細江町小野"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.821228,
               137.650788
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"細江町気賀"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.804083,
               137.638602
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"細江町中川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.806585,
               137.683156
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"細江町広岡"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.811721,
               137.659749
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"細江町三和"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.820414,
               137.684082
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町井伊谷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.830592,
               137.675655
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町伊平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.864832,
               137.663500
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町奥山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.840485,
               137.620717
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町金指"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.821902,
               137.679899
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町狩宿"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.858143,
               137.604148
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町川名"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.871863,
               137.703331
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町黒渕"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.836845,
               137.654158
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町渋川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.930174,
               137.680644
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町四方浄"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.889407,
               137.667123
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町白岩"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.841692,
               137.659757
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町田沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.908315,
               137.654524
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町田畑"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.848807,
               137.648463
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町栃窪"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.835603,
               137.648085
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町兎荷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.854021,
               137.678202
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町西久留女木"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.907797,
               137.698418
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町西黒田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.875812,
               137.638317
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町花平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.848078,
               137.668849
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町東久留女木（３７２～７９９番地）"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.893944,
               137.726411
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町東黒田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.881001,
               137.653372
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町別所"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.895283,
               137.680322
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町的場"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.890918,
               137.649352
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町三岳"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.842315,
               137.694066
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町谷沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.869804,
               137.627472
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"引佐町横尾"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.835967,
               137.661337
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"神宮寺町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.831449,
               137.668999
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町宇志"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.809365,
               137.565239
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町大崎"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.771831,
               137.565240
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町大谷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.813552,
               137.592894
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町岡本"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.814583,
               137.543996
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町上尾奈"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.785750,
               137.511578
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町駒場"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.801982,
               137.581794
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町佐久米"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.793256,
               137.602905
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町下尾奈"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.782707,
               137.536630
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町只木"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.838134,
               137.573010
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町都筑"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.790279,
               137.581279
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町津々崎"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.801076,
               137.572208
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町釣"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.814364,
               137.532626
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町鵺代"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.798373,
               137.544908
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町日比沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.806440,
               137.527216
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町平山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.828969,
               137.521632
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町福長"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.834711,
               137.548063
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町本坂"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.808325,
               137.505292
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町摩訶耶"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.818664,
               137.557952
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"三ヶ日町三ヶ日"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.806878,
               137.552249
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"寺島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.781478,
               137.795346
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中条"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.782818,
               137.781097
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"横須賀"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.788298,
               137.789901
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"高畑"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.793433,
               137.797978
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西美薗"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.802522,
               137.796372
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東美薗"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.798368,
               137.803566
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"油一色"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.804352,
               137.807550
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"本沢合"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.811687,
               137.799048
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"道本"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.804093,
               137.791109
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"沼"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.792959,
               137.786601
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"貴布祢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.797366,
               137.783606
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"小林"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.805440,
               137.787224
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"善地"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.789856,
               137.807789
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"高薗"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.788367,
               137.817210
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"竜南"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.783172,
               137.815573
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"新堀"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.792584,
               137.815309
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"八幡"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.799614,
               137.815609
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"永島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.808538,
               137.815991
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上善地"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.798680,
               137.810117
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"小松"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.788826,
               137.771531
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"内野"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.784107,
               137.757065
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"内野 "
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.783015,
               137.749778
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"平口"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.801464,
               137.759129
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"染地台"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.791622,
               137.745083
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.848148,
               137.818068
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"中瀬"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.830113,
               137.817658
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"豊保"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.829862,
               137.804560
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"於呂"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.836760,
               137.800256
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"根堅"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.843667,
               137.790283
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"尾野"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.836731,
               137.778421
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"宮口"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.823891,
               137.767245
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"新原"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.813985,
               137.784468
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.850039,
               137.740351
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"堀谷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.870546,
               137.759806
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"灰木"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.845854,
               137.759237
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"四大地"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.855779,
               137.754310
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西中瀬"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.822578,
               137.806661
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"二俣町二俣"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.862550,
               137.813845
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"二俣町大園"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.878540,
               137.807410
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"二俣町阿蔵"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.867691,
               137.838365
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"二俣町鹿島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.851515,
               137.807516
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"二俣町南鹿島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.842427,
               137.808603
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"山東"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.888899,
               137.836954
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"次郎八新田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.8738049,
               137.8198027
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大谷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.877466,
               137.815370
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"船明"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.888699,
               137.818700
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"只来"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.891647,
               137.855039
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"横川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.905564,
               137.882982
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"横山町"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.949248,
               137.800313
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"月"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.924539,
               137.803256
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"小川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.941761,
               137.858058
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"相津"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.918993,
               137.818697
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"伊砂"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.906278,
               137.811102
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.905854,
               137.824372
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.917848,
               137.840590
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"谷山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.931592,
               137.822508
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西雲名"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.952342,
               137.824617
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東雲名"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.954971,
               137.839640
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"熊"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.964913,
               137.752438
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"神沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.944357,
               137.714026
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"大栗安"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.942169,
               137.734415
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"西藤平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.915788,
               137.763799
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"東藤平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.928251,
               137.781831
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"阿寺"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.942019,
               137.761992
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"芦窪"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.926697,
               137.754064
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"長沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.916575,
               137.741045
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"懐山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.922184,
               137.724098
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"石神"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.899280,
               137.761480
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"上野"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.886628,
               137.773080
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"両島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.886659,
               137.792218
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"青谷"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.869137,
               137.782986
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"渡ケ島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.864501,
               137.803990
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"米沢"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.897894,
               137.798566
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"緑恵台"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.866017,
               137.798233
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町領家"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.951370,
               137.886011
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町堀之内"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.955783,
               137.908578
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町胡桃平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.958737,
               137.956055
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町和泉平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.964769,
               137.931177
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町砂川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.972758,
               137.948450
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町大時"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.969290,
               137.971903
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町長蔵寺"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.987709,
               137.938660
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町石打松下"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.001877,
               137.934951
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町田黒"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.000167,
               137.946633
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町筏戸大上"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.006958,
               137.953771
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町五和"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.015150,
               137.948684
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町越木平"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.006980,
               137.971400
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町田河内"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.005699,
               138.010296
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町牧野"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.986994,
               137.966279
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町花島"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.988716,
               137.987053
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町杉"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.027305,
               137.967468
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町川上"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.044046,
               138.020334
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町宮川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.992612,
               137.888129
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町気田"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.014789,
               137.893985
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町豊岡"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.060239,
               137.920222
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"春野町石切"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.049214,
               137.974823
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町浦川"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.028139,
               137.749420
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町川合"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.078922,
               137.784643
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町半場"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.070375,
               137.807823
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町中部"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.083534,
               137.797027
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町佐久間"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.115025,
               137.817682
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町奥領家"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.145404,
               137.842165
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町相月"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.121284,
               137.870074
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町戸口"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.065884,
               137.830244
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町上平山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.036814,
               137.867185
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"佐久間町大井"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.085348,
               137.863037
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"水窪町奥領家"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.226016,
               137.906956
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"水窪町地頭方"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.221054,
               137.974735
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"水窪町山住"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.140512,
               137.942359
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"龍山町大嶺"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.982932,
               137.799301
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"龍山町戸倉"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               34.975469,
               137.845554
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"龍山町下平山"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.002996,
               137.848112
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
            "Name":"龍山町瀬尻"
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               35.025132,
               137.821533
            ]
         }
      }
   ]
}